[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "quarto-website-template"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
python = ">=3.11"
requests = ">=2.31.0"
deepdiff = ">=6.7.1"
pyyaml = ">=6.0.3,<7"
pandas = ">=2.1.3"
tabulate = ">=0.9.0"
jupyter = ">=1.1.1,<2"
nbformat = ">=5.9.2"
plotly = ">=5.18.0"
